#:schema https://gitlab.com/-/snippets/3726568/raw/main/gleam-toml-schema.json

name = "flatpak_list_updates"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleamyshell = ">= 2.0.2 and < 3.0.0"
